### ISSUE TITLE
Inline webform widget: add a setting so automatic inline display can happen not only for new ADOs

### ISSUE THREAD

**Issue by DiegoPino** [esmero/webform_strawberryfield#100]
# What?

The inline webform widget shows right now a fully rendered webform for new ADOs but shows a button you may want to click for existing ADOs. 

![image](https://user-images.githubusercontent.com/6946023/105770269-f5162100-5f2c-11eb-832d-4057554e0b97.png)

This logic makes sense if, e.g, you just want to update the display mode, or the user but do not want to edit the metadata , because when the form is inline we do hide the main submit button so people do not have a confusing 2x submit button thing on display... how to deal with that forever by making the webform submit also, -after its own submit handler- trigger the global node submit is something "special" I have reserved for @pcambra in the near future!.

But for simple uses cases where the user has a very limited role an really no NODE level interaction other than editing metadata is even allowed, having a setting that allows us to directly show the form always IS super desired.

So desired that I even left a comment there in the code..

https://github.com/esmero/webform_strawberryfield/blob/1.0.0-RC1/src/Plugin/Field/FieldWidget/StrawberryFieldWebFormInlineWidget.php#L334-L337

# How to do this?

- Add a new setting (checkbox) that by default acts the way it acts now
- Add a config entry to our widget schema (so drupal does not drive us crazy with invalid settings notifications)
- Add another setting for the "cancel" form button (which appears inside the editing once its enabled.. why?) because we may also do not need that one for this type of users, but other users may have it, so they can go back to "globally" edit the node and not just the metadata, depicted here:
![image](https://user-images.githubusercontent.com/6946023/105770311-03643d00-5f2d-11eb-811c-cb1c3bb6ec26.png)

**Comment by DiegoPino** [comment]
@alliomeria ping. This is what we "just" discussed

**Comment by patdunlavey** [comment]
@DiegoPino I added a comment: https://github.com/esmero/webform_strawberryfield/commit/04867f1ccaef066c4a5a147946ba487d7213ca56#r47431992

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/webform_strawberryfield/commit/6702a7ac65ec2a418c5e61fc691de5fa11be3fbc
