### ISSUE TITLE
Provide EDTF validation for webform field

### ISSUE THREAD

**Issue by patdunlavey** [esmero/webform_strawberryfield#102]
Provide extended date time format (EDTF) validation by either:
1. An additional form element validation option (a set of three options) for general text fields; or
2. A custom form element for EDTF dates, which consists of a text field, with the ability to configure three options for validation.

The three validation options are based on utilizing [EDTFUtils::validate()](https://github.com/Islandora/controlled_access_terms/blob/8.x-1.x/src/EDTFUtils.php#L132)
1. Are interval expressions permitted?
2. Are set expressions permitted?
3. Are only valid calendar dates permitted?

The first choice - to simply add edtf validation as an option for basic textfield elements would, I think, be preferred.

**Comment by patdunlavey** [comment]
I spent some hours trying to figure out how to do this as a learning exercise. I've figured out how to add and configure a custom webform element, but the actual form element is not appearing on the form - though its validation callback is getting called when the webform is submitted! 
I also spent a good bit of time trying to figure out how one is supposed to customize the form validation options for a standard text field (which would be my preferred solution), but didn't get anywhere with that at all.

**Comment by DiegoPino** [comment]
@patdunlavey webform elements are made of two classes. One (plugin) in the WebformElement space and one in the Element (core) space, this last one is the actual render element. Both need to share the same ID.  `webform_strawberryfield` is full of examples, from super simple ones to more complex ones. Without seeing your code I'm blind to what part is missing.

For the EDTF validated element I would suggest (strongly) you either extend of improve the https://github.com/esmero/webform_strawberryfield/blob/ISSUE-100/src/Plugin/WebformElement/WebformMetadataDate.php. This element has an exposed choice of single date, range and free form date. By adding an extra option in its config form and then, in its validation handlers (many for a date element) a check for ETDF format you would also allow current users to use this feature. Overriding "any" text element is not an easy task and feels almost hack-ish but I guess you can also do that. Text elements have a choice for a pattern based validation (regular expression) that you may want to override/extend if that is your choice.

Let me know if this is a task/issue you are going to spend time coding so I assign to you, or more like a feature request I may need to put into the roadmap (competing with many other pending needs)

Finally: ETDF is not something that will make any sense to Solr, so you want to either build a processor for these or a smart new Key Name Provider plugin that can read ETDF but cast into actual Solr aware Dates (even ranges) by replacing all the XX with actual ISO8601 dates.

**Comment by patdunlavey** [comment]
Thanks for the tips, @DiegoPino. I like the idea of extending the WebformMetadataDate, and will take a whack at that. I'm assigning this to myself.

**Comment by patdunlavey** [comment]
Thanks @DiegoPino 

I modified `Plugin\WebformElement\WebformMetadataDate.php` and `\Element\WebformMetadataDate.php`. I also added a minimally modified copy of Seth Shaw's EDTFUtils.php to `Tools\EDTFUtils.php`. (I'm not sure if this is the right place to put this. Will discuss this in a bit.)

They add configuration to the webform component as follows:
- When "show freeform always" is checked, a new checkbox appears: "Validate as EDTF"
- When "Validate as EDTF" is checked, three new checkboxes appear: "Are interval expressions permitted?", "Are set expressions permitted?" and "Are only valid calendar dates permitted?"

Then, in `\Drupal\webform_strawberryfield\Element\WebformMetadataDate::validateMetadataDates` I added
```php

    // Perform edtf validation on freeform date if so configured.
    if(!empty($metadatadate_element['#edtf_validateme']) && !empty($element['#value']['date_free'])) {
      $intervals = $metadatadate_element['#edtf_validate_option_intervals'] ?? FALSE;
      $sets = $metadatadate_element['#edtf_validate_option_sets'] ?? FALSE;
      $strict = $metadatadate_element['#edtf_validate_option_strict'] ?? FALSE;
      $validation_errors = EDTFUtils::validate($element['#value']['date_free'], $intervals, $sets, $strict);
      if (!empty($validation_errors)) {
        // @TODO: Figure out how to get the error message to display for $element['date_free'] only.
        // @TODO: If $form_state->setErrorByName($element['date_free'],...) is used, no error message appears.
        $form_state->setError($element,
          t('The extended date time format string for the @name field is invalid. @messages',
            [
              '@name' => $element['#title'],
              '@messages' => implode("\n", $validation_errors),
            ]));
      }
    }
```

This is pretty close to the way that I think we want it to work. The next question is getting the date string indexed in solr, and that's where I could use some direction. 

Some thoughts/observations:
- I wrote a pretty elaborate bunch of code for CAR that, in addition to converting EDTF date strings to dates, date ranges, and multi-value dates, also provides an extensible system for translating a pretty broad range of date formats, not just EDTF. I could see trying to package that up into, what, a service? (If so, pointers on how to do that would be welcome.) If I do that, then I should probably put the validation service discussed above for webform_strawberryfield into the same place.
- In any case,  I could use help determining how to implement the solr indexing piece. I played a bit with extending `\Drupal\strawberryfield\Plugin\DataType\StrawberryValuesViaJmesPathFromJson` and `\Drupal\strawberryfield\Plugin\StrawberryfieldKeyNameProviderBase`, though I haven't figured out how to get them to actually fire. Here's what I have for the annotation on that class:
```php
/**
 *
 * Strawberry Field Key Date Provider
 *
 * @StrawberryfieldKeyNameProvider(
 *    id = "datejmespath",
 *    label = @Translation("JmesPath Strawberry Field Key Date Provider"),
 *    processor_class = "\Drupal\strawberryfield\Plugin\DataType\StrawberryDatesViaJmesPathFromJson",
 *    item_type = "date"
 * )
 */
class JmesPathDateProvider extends StrawberryfieldKeyNameProviderBase {
...
```
Does this approach seem promising? Is the "build a processor" approach you mentioned better, and if so (only if so!!), can you elaborate a bit on that?

**Comment by DiegoPino** [comment]
@patdunlavey I'm normally all about OSS collaboration and sharing but since that code in particular is not part of a package/library but core to I8 I prefer we do not copy it (at all), also not easy to attribute and the classes are not very compliant with actual Element/data validation. I feel it would also be felt as "scrapping" that project and we do are not much into scrapping.  I looked at the code and there is tons that can be improved/simplified for our use case. But its a good exercise and I'm ok with testing functionality first and then form/adapting to a merge pull later.

But also: 

> I wrote a pretty elaborate bunch of code for CAR that, in addition to converting EDTF date strings to dates, date ranges, and multi-value dates, also provides an extensible system for translating a pretty broad range of date formats, not just EDTF
Sincen you wrote this already, can we not validate based on the actual date conversion? Like you pass the EDTF, you convert, if the conversion is actually a valid date then EDTF is valid? Just an idea

Can you share your Branch so I can give it a look? All what you say makes sense to me. The Key Name Provider can go in this module too (to share code), since any module that depends on SBF can provide plugins.

I will give you a hand with the Plugin, sadly a busy afternoon, can that be done tomorrow AM?

Looking forward to see your code. This all sounds amazing!

**Comment by patdunlavey** [comment]
@DiegoPino I pushed the WIP code here: https://github.com/Born-Digital-US/webform_strawberryfield/tree/ISSUE-102.

Yes, I'm just scraping Seth's code. For CAR, I pretty much wrote everything from scratch. If you think Seth's code is overwrought and messy, I'm pretty sure you'll be appalled with mine! We had a huge amount of hand-entered dates to fix, which is what drove my implementation. It's on gitlab; not public. If you have a gitlab account, I could share it with you, or I could put it somewhere else that you can access.

**Comment by DiegoPino** [comment]
@patdunlavey I'm fine (and happy) to look at your gitlab code, I do have an account but if you plan on submitting/committing it (and we can reshape and clean, important thing is you know already it works) a simple utility class would be enough, no need for Service here (yet).

I do not feel really that Seth's code is messy, I may rephrase that, its just in a different coding style and cover other needs, but main concern for me is that is also bundled for I8/inside I8 and I want to respect that or we will all end copy pasting. 

Also adding to the discussion:

- EDTF level 0, 1, 2 and 3 JS library https://github.com/inukshuk/edtf.js
- A ruby one https://github.com/inukshuk/edtf-ruby

Both look promising and may do way more than what we need here. The main questions is, what type of EDTF is (list, single date) and if the pattern matches or not
 The actual Key name provider will have to "parse it" and see if it can be casted to a close/good enough ISO 8601-1 representation, either single or a range (in this case single plugin with options) since you can not index both inside the same Solr field. The idea of the key name provider should be also be able to deal with any other date/string that can be seeing as a date natively.

Thanks a lot @patdunlavey

**Comment by patdunlavey** [comment]
@DiegoPino part of my thinking about a service is thinking that we would (or may) be using this functionality both in strawberryfield and webform_strawberryfield. I'll have more thoughts later, after a meeting...

**Comment by DiegoPino** [comment]
@patdunlavey sure, can also be a service if you want. In that case it would need to go in SBF if you want to use it there since the dependencies as webform_strawberryfield depends on strawberryfield.

**Comment by patdunlavey** [comment]
{Capturing yesterday's discussion from slack:}

> Diego Pino  4:17
> @Pat Dunlavey we may want to test how Drupal/Search API deals with the infinite ranges
> 4:17
> https://lucene.apache.org/solr/guide/8_8/working-with-dates.html
> 4:17
> e.g if we want to say something has happened since ever to NOW
> 4:17
> or, as a range
> 4:17
> its valid from last week to FOREVER
> 4:17
> because its unknown
> 4:18
> the [* TO SOMEDATE]
> 
> Pat Dunlavey  4:18 PM
> hmm... haven't looked at that
> 
> Diego Pino  4:18 PM
> I will check solarium
> 4:21
> So.. some advances on the Key name provider for date/date ranges.
> 4:22
> It will inherit (Type data structure) of
> 4:22
> \Drupal\datetime_range\Plugin\Field\FieldType\DateRangeItem
> 4:22
> DataDefinition::create('datetime_iso8601')
> 4:23
> The idea is that the key name provider will be wrapped around a class (List)
> 
> Pat Dunlavey  4:23 PM
> for the purposes of what I'm working on, my thinking has been that all indexed dates in solr would be full-precision dates, but with attributes "start" and "end" and possibly qualifier ("approximate', etc). I'm not thinking  about how to represent in drupal. But maybe I should be.
> 
> Diego Pino  4:23 PM
> The simples use case is the best to start
> 4:24
> once we have that clean and working we can go "edge" and "super picky user" based
> 4:24
> (that is how i feel normally)
> 
> Pat Dunlavey  4:24 PM
> ha, I already thought I was at that ragged edge!
> :+1::skin-tone-4:
> 1
> 
> 
> Diego Pino  4:24 PM
> So this is the item definition
> 4:24
> $properties['value'] = DataDefinition::create('datetime_iso8601')
>   ->setLabel(t('Start date value'))
>   ->setRequired(TRUE);
> $properties['start_date'] = DataDefinition::create('any')
>   ->setLabel(t('Computed start date'))
>   ->setDescription(t('The computed start DateTime object.'))
>   ->setComputed(TRUE)
>   ->setClass(DateTimeComputed::class)
>   ->setSetting('date source', 'value');
> $properties['end_value'] = DataDefinition::create('datetime_iso8601')
>   ->setLabel(t('End date value'))
>   ->setRequired(TRUE);
> $properties['end_date'] = DataDefinition::create('any')
>   ->setLabel(t('Computed end date'))
>   ->setDescription(t('The computed end DateTime object.'))
>   ->setComputed(TRUE)
>   ->setClass(DateTimeComputed::class)
>   ->setSetting('date source', 'end_value');
> return $properties;
> 4:25
> That will be wrapper around a generic List one using a custom item entry
> 4:25
> and that way we get Many possible ranges for a single property
> 
> ....
> 
> Diego Pino  4:25 PM
> I wonder if we can just go "computed"
> 4:26
> Ok, back to JMESPATH then, good luck
> 
> ....
> 
> Diego Pino  4:41
> @Pat Dunlavey will leave this here and will walk away slowwly..
> https://carbon.nesbot.com/docs/#api-json
> carbon.nesbot.comcarbon.nesbot.com
> Carbon - A simple PHP API extension for DateTime.
> Carbon - A simple PHP API extension for DateTime.
> 4:41
> for tomorrow
> 4:45
> and we can also try https://book.cakephp.org/chronos/2/en/index.html
> 4:45
> Ok, disconnecting because i may have overdone communication today
>

**Comment by patdunlavey** [comment]
A lot of conversations on this topic over in Islandora land: https://github.com/Islandora/documentation/issues/1748

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/webform_strawberryfield/commit/680270b3bda51832b5170e4a43255158f5ccd214
