### ISSUE TITLE
Webform element metadata date nuisance error

### ISSUE THREAD

**Issue by patdunlavey** [esmero/webform_strawberryfield#115]
# What?

Getting a missing index notice when loading the metadata date form element: "data-drupal-date-format"

**Comment by DiegoPino** [comment]
@patdunlavey can you share your Webform element setting (the YML file from the Webform YML Source). That way I can check and fix

Thanks!

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/webform_strawberryfield/commit/58d58e6499c6cb11c08c8758fcaaf649914f5686

Thanks @patdunlavey
