### ISSUE TITLE
Europeana API changed their base URLs

### ISSUE THREAD

**Issue by DiegoPino** [esmero/webform_strawberryfield#142]
# what?

Yes, new URLS so older Entity API calls are wrong. Fixing (Thanks to @alliomeria for finding this out, so fast, so fast).

Also we will document and encourage each user to get their own Europeana API keys IF they decide to use the endpoints

For the historic recreation see https://github.com/esmero/webform_strawberryfield/pull/123

**Comment by aksm** [comment]
Resolved by 0bf7e788c6a8eccbc343bfcd1a046d6508b0eede, and documented by f81d051fa2a48917cdd60de0cd4a7f568a7a83e4.
