### ISSUE TITLE
How to get face decection working?

### ISSUE THREAD

**Issue by fishfree** [esmero/webform_strawberryfield#166]
I use the IIIF Openseadragon viewer formatter, when clicking the face detection icon, nothing happened, and even on the editing ADO page, there is no tips for saving or discarding unsaved annotations.
![image](https://github.com/esmero/webform_strawberryfield/assets/1741341/c42de4c8-674e-4657-93cf-19711401a74b)
![image](https://github.com/esmero/webform_strawberryfield/assets/1741341/2257dcd5-0082-46cd-b779-29d7ad3a230a)

**Comment by DiegoPino** [comment]
Face detection is a modifier. Once to toggle it in you need to make a selection around a region of interest. How accurate it is will depend on the zoom level too. We have tested this even with group photos (old ones) with good results

**Comment by fishfree** [comment]
I see how to use it: firstly select the face-detection icon, then select the rectangle icon, select a region in the image, then faces in the selected region will be automatically detected and the annotation dialogue shows up.
Thank you for your tip.
