### ISSUE TITLE
Add features to custom Webform LoD from CSV attached to an ADO suggest

### ISSUE THREAD

**Issue by livsolis** [esmero/webform_strawberryfield#177]
I would like to add a couple of features to the Webform LoD from CSV attached to an ADO suggest:

1. An additional optional field that is autocomplete-able based on the selected term. If possible, this field is disabled by default and only appears when an webform element option is selected as it won't be necessary for most fields. This extra information would be in an additional column in the CSV attached to the ADO used for the autocomplete.

• Use case: In addition to the URL/URI, I would like to store "type" (personal, corporate, family) for names.

2. I would like the element to be configurable to display contextual information for disambiguation, akin to display in Getty AAT/Wikidata LoD fields. I would like the contextual information to appear in a specific column in the CSV attached to the ADO linked to the element. If a setting like "Display contextual information" is checked in the build options, the user then identifies the column to be appended to the term (e.g. in parentheses).

3. In addition to these features, there appears to be an issue with the **Contains** option in the **Autocomplete matching operator** settings. I would expect the **Contains** option to search and match the text entered in the label field, but that appears not to be happened. In the first screenshot below, the form is set to **Starts with**. In the second, it is set to **Contains**. "Diego" should be sufficient to identify the California place location, but the field doesn't match the text to anything in the CSV used to set up the element.
<img width="392" alt="Screenshot 2024-06-18 at 9 57 02 AM" src="https://github.com/esmero/webform_strawberryfield/assets/16403067/84cd7254-bfb3-44a0-b2a8-e7886cb6404a">
<img width="412" alt="Screenshot 2024-06-18 at 9 58 21 AM" src="https://github.com/esmero/webform_strawberryfield/assets/16403067/b36ce716-e22b-4f6a-b9e0-20a56f1dd21f">

**Comment by alliomeria** [comment]
Thanks for opening this request for updates to this Custom Webform LoD from CSV element @livsolis ! We'll take a look at these different items and follow up with you in the upcoming weeks. :)

**Comment by alliomeria** [comment]
Also noting that you communicated over email about the possibility that for an instance where this element is Limited to a single value, the autocomplete functionality might not work properly. We'll look into that too. 

Thanks again!

**Comment by DiegoPino** [comment]
@livsolis, thanks for documenting your findings are new feature needs and thanks @alliomeria for encouraging and following up the discussions here and in Slack. 
I will try to make some space tonight to tackle first:
- Bug (single v/s multi elements issue)
- Starts with V/s Contains 

And then, maybe Thursday? see if we can work on new features. Thanks a lot again

**Comment by DiegoPino** [comment]
Closed as completed, the Agents part will be covered in https://github.com/esmero/webform_strawberryfield/issues/179
