### ISSUE TITLE
Allow webform confirmation message to be overridden by an Admin

### ISSUE THREAD

**Issue by DiegoPino** [esmero/webform_strawberryfield#74]
# What? Override? Let people decide? What is this, democracy?

Well, yes. It is!

Now we have this default: "Thanks, you are all set! Please Save the content to persist the changes." but maybe people want their own, so we respect people's choices (also VOTE)

**Comment by DiegoPino** [comment]
See https://github.com/esmero/webform_strawberryfield/pull/70/commits/1d4b35e36ac682a1f8a3c45a77e6fefaf39d95ed
Will get merged with ISSUE-69 once I get the tabular/CSV editor in place. Almost there

**Comment by DiegoPino** [comment]
@alliomeria will update the sites you are working on with this later tonight

**Comment by alliomeria** [comment]
@DiegoPino Great! Power to the people! :) Thank you very much.

**Comment by DiegoPino** [comment]
Closing as solved. This is in RC1
