### ISSUE TITLE
Hotspot URL linking 

### ISSUE THREAD

**Issue by hulsmacmbsc** [esmero/webform_strawberryfield#98]
Hotspot URL linking:  It appears that the cursor identifies the hotspot as a hyperlink, but it does not activate the opening of the URL. I looked in the JSON for links I created and they are listed as "type": "info" and URL value is null. 

Example Link from [https://esie.space/do/7766ae09-39b9-4f1a-bc6a-1b84347c3431](url)
JSON:
   "id": "panorama_tour_185_2eee6872-3c08-4a6c-a0b4-e97b5a22215a",
                    "URL": null,
                    "yaw": "175.0597638717715",
                    "text": "Test URL Link Hotspot",
                    "type": "info",
                    "pitch": "19.252588296505806"

If I replace "URL": null, **WITH** "URL": "https://library.buffalostate.edu/home/print", 

there is a moment where the browser seems to want to open it automatically. However, right-clicking and selecting open in new tab does work.

As of now, creating the hotspot as External URL and entering URL does not activate the link. 
Thanks! :)

**Comment by DiegoPino** [comment]
@hulsmacmbsc will check on this. I remember this was working at certain moment so may be just a miss in one of the latest releases. Should be easy. Won't be fixed today (sorry) but is on my list!

**Comment by hulsmacmbsc** [comment]
No rush here @DiegoPino! Enjoy your weekend! Let me know if I can help

**Comment by DiegoPino** [comment]
@hulsmacmbsc @powerman5000 re: external Links. I have (finally a fix for this) but wanted to be sure I get this right. These External URLS will open in a new Browser window. Not a frame or Popup just to make sure its clean/clear the data is not managed by you. I'm not sure how that will work for Full screen... wonder if we can do some testing/expectation discussion here? Thanks a lot for your patience, we have too many moving parts everywhere and this required some re-understanding of my code. 

Any feedback is appreciated

**Comment by DiegoPino** [comment]
@hulsmacmbsc @powerman500 better late than never. Sorry, took me some time because we are a bit overworked here but its solved.
https://github.com/esmero/webform_strawberryfield/pull/118 fixes the issue and https://github.com/esmero/format_strawberryfield/pull/152 complements with Proper Linking in the viewer. This will be usable tomorrow on https://esie.space (by noon)

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/webform_strawberryfield/commit/a849989809c02d6ff94cfc691893f9e12e4c6660
